#!/usr/bin/env ruby
# frozen_string_literal: true

require "pathname"
require "eddie/jekyll"

site_dir = ARGV[0]
unless site_dir
  warn "usage: eddie-jekyll-install <site-dir> [asset-root]"
  exit 1
end

root = Pathname.new(__dir__).join("..").expand_path
script = root.join("scripts", "install.sh")
env = {
  "EDDIE_RELEASE_VERSION" => ENV.fetch("EDDIE_RELEASE_VERSION", Eddie::Jekyll::VERSION)
}

if ARGV[1]
  exec(env, "bash", script.to_s, File.expand_path(site_dir), File.expand_path(ARGV[1]))
else
  exec(env, "bash", script.to_s, File.expand_path(site_dir))
end
