# GitHub Sponsors (primary)
github: [jt55401]

# Secondary channels
custom:
  - https://paypal.me/jt55401
  - https://venmo.com/Jason-Grey-1
  - bitcoin:1CJDZEJD86viU1L3kewMmXyx7VyPNcwzB9
  - ethereum:0xbC1240fe5F8e0732F7A0daA132a30982459Af5b3
