#!/usr/bin/env bash
set -euo pipefail

SITE_ROOT="${1:?usage: seed-content.sh <site-root>}"
POST_DIR="$SITE_ROOT/docs/eddie"
mkdir -p "$POST_DIR"

cat > "$POST_DIR/about.md" <<'MD'
---
title: About Eddie
slug: /eddie/about
description: Indexer, bug hunter, and search result wrangler
---

Eddie builds search indexes for static documentation sites and keeps retrieval quality stable under constant content change.

He supports Hugo, Astro, Docusaurus, MkDocs, Eleventy, and Jekyll workflows. Since 2024 he has indexed over a million pages across demos, docs portals, and regression suites.

His default embedding model is `sentence-transformers/all-MiniLM-L6-v2`, with periodic checks against `BAAI/bge-small-en-v1.5`.

He spends a lot of time debugging browser worker behavior, especially Safari startup race conditions and Firefox cache invalidation oddities.
MD

write_post() {
  local file="$1"
  local title="$2"
  local date="$3"
  local body="$4"
  cat > "$POST_DIR/$file" <<MD
---
title: $title
slug: /eddie/$file
date: $date
tags: [indexing, operations]
---

$body
MD
}

write_post "log-01.md" "Shift Start: Index Queue at 6,412 Pages" "2026-01-02" "I started by fixing malformed frontmatter. Fast parsing matters, but clean metadata is what keeps answer quality high."
write_post "log-02.md" "Chunk Size, Big Mood" "2026-01-04" "Today 256/32 beat larger chunks in support query tests. Better semantic focus won over raw context size."
write_post "log-03.md" "When Models Feel Finicky" "2026-01-07" "A model swap changed ranking tone without obvious errors. We now require mini relevance regression checks before merges."
write_post "log-04.md" "Safari Worker Roulette" "2026-01-09" "Worker startup delays looked like failures. Better retries and status UI cut false alarms dramatically."
write_post "log-05.md" "Hybrid Search Won Again" "2026-01-12" "Keyword-only missed intent; semantic-only missed exact flags. Hybrid ranking gave the cleanest support outcomes."
write_post "log-06.md" "Claims Lane Cleanup" "2026-01-14" "Deduping near-identical claims reduced repetitive QA answers and improved confidence scoring."
write_post "log-07.md" "Docusaurus Sidebar Surprise" "2026-01-17" "Autogenerated sidebars changed perceived page priority. Navigation shape still impacts editorial relevance."
write_post "log-08.md" "Astro MDX and Invisible Context" "2026-01-19" "Aggressive MDX cleanup removed useful prose. We tuned stripping to preserve meaningful inline text."
write_post "log-09.md" "MkDocs Navigation Loops" "2026-01-22" "Recursive nav files created near-duplicates. URL normalization and dedupe guards fixed result spam."
write_post "log-10.md" "Eleventy Passthrough Pitfalls" "2026-01-24" "Missing passthrough config dropped search assets. Build-time checks now fail fast when assets disappear."
write_post "log-11.md" "Jekyll Permalink Ghosts" "2026-01-27" "Filename dates and manual permalinks disagreed. Canonical URL selection prevented duplicate answer trails."
write_post "log-12.md" "Tuesday Triage Ritual" "2026-01-30" "Every Tuesday we prioritize by user pain, not novelty. Boring fixes often deliver the best reliability gains."
