#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-only
#
# Build the Eddie browser widget.
# Produces dist/ with five files ready to deploy alongside a Hugo site:
# eddie.wasm, eddie-wasm.js, eddie-worker.js, eddie-widget.js, eddie-agent-worker.js.

set -euo pipefail

# `--js-only` skips the WASM build and only re-assembles the JS bundles from
# an existing widget/pkg/ (fast iteration on the widget and workers).
JS_ONLY=0
for arg in "$@"; do
  case "$arg" in
    --js-only) JS_ONLY=1 ;;
    *) echo "unknown argument: $arg" >&2; exit 2 ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
NPM_SCOPE="${NPM_SCOPE:-jt55401}"

WASM_PACK_SCOPE_ARGS=()
if [[ -n "$NPM_SCOPE" ]]; then
  WASM_PACK_SCOPE_ARGS+=(--scope "$NPM_SCOPE")
fi

# Cargo.toml's release profile is opt-level=3 for the native CLI; the WASM
# build trades speed for size. Override either by exporting the variable.
# (panic=abort was measured on 2026-08-28: +0 bytes after brotli, so it stays off.)
export CARGO_PROFILE_RELEASE_OPT_LEVEL="${CARGO_PROFILE_RELEASE_OPT_LEVEL:-s}"

if (( JS_ONLY )); then
  [[ -f "$SCRIPT_DIR/pkg/eddie_bg.wasm" ]] || { echo "--js-only needs an earlier full build (widget/pkg/ is missing)" >&2; exit 1; }
else
echo "==> Building WASM module (opt-level=$CARGO_PROFILE_RELEASE_OPT_LEVEL)..."
wasm-pack build "$PROJECT_ROOT" \
  "${WASM_PACK_SCOPE_ARGS[@]}" \
  --target no-modules \
  --out-dir "$SCRIPT_DIR/pkg" \
  --out-name eddie \
  --release

WASM_BIN="$SCRIPT_DIR/pkg/eddie_bg.wasm"
if command -v wasm-opt >/dev/null 2>&1; then
  echo "==> Running candidate WASM optimization (wasm-opt -Oz --all-features)..."
  WASM_OPT_CANDIDATE="$(mktemp)"
  cp "$WASM_BIN" "$WASM_OPT_CANDIDATE"
  wasm-opt -Oz --all-features "$WASM_OPT_CANDIDATE" -o "$WASM_OPT_CANDIDATE"

  if command -v brotli >/dev/null 2>&1; then
    base_br="$(brotli -q 11 -c "$WASM_BIN" | wc -c | tr -d ' ')"
    opt_br="$(brotli -q 11 -c "$WASM_OPT_CANDIDATE" | wc -c | tr -d ' ')"
    if (( opt_br < base_br )); then
      mv "$WASM_OPT_CANDIDATE" "$WASM_BIN"
      echo "==> Applied wasm-opt candidate (brotli bytes: $base_br -> $opt_br)."
    else
      rm -f "$WASM_OPT_CANDIDATE"
      echo "==> Skipped wasm-opt candidate (brotli bytes: $base_br -> $opt_br, no gain)."
    fi
  else
    base_raw="$(wc -c <"$WASM_BIN" | tr -d ' ')"
    opt_raw="$(wc -c <"$WASM_OPT_CANDIDATE" | tr -d ' ')"
    if (( opt_raw < base_raw )); then
      mv "$WASM_OPT_CANDIDATE" "$WASM_BIN"
      echo "==> Applied wasm-opt candidate (raw bytes: $base_raw -> $opt_raw)."
    else
      rm -f "$WASM_OPT_CANDIDATE"
      echo "==> Skipped wasm-opt candidate (raw bytes: $base_raw -> $opt_raw, no gain)."
    fi
  fi
else
  echo "==> wasm-opt not found; skipping optional WASM optimization pass."
fi
fi # JS_ONLY

echo "==> Assembling dist/..."
mkdir -p "$PROJECT_ROOT/dist"
cp "$SCRIPT_DIR/pkg/eddie_bg.wasm" "$PROJECT_ROOT/dist/eddie.wasm"
cp "$SCRIPT_DIR/pkg/eddie.js"      "$PROJECT_ROOT/dist/eddie-wasm.js"

# Each JS entry point is the concatenation of the pure modules it uses
# (widget/src/lib/*.js, exposed as `EddieLib`) and its main file. No bundler:
# the lib files attach to a lexical `EddieLib` when one is in scope.
bundle() {
  local out="$1"; shift
  local main="$1"; shift
  local wrap="$1"; shift
  {
    echo "// SPDX-License-Identifier: GPL-3.0-only"
    echo "// Generated by widget/build.sh from widget/src/$main and widget/src/lib/*.js; edit those instead."
    if [[ "$wrap" == "iife" ]]; then echo "(function () {"; fi
    echo '"use strict";'
    echo "const EddieLib = {};"
    for lib in "$@"; do
      cat "$SCRIPT_DIR/src/lib/$lib"
      echo
    done
    cat "$SCRIPT_DIR/src/$main"
    if [[ "$wrap" == "iife" ]]; then echo "})();"; fi
  } > "$out"
  node --check "$out"
}

bundle "$PROJECT_ROOT/dist/eddie-worker.js"       worker.js             plain urls.js lanes.js download.js
bundle "$PROJECT_ROOT/dist/eddie-widget.js"       eddie-widget.js       iife  config.js urls.js lanes.js agent.js
bundle "$PROJECT_ROOT/dist/eddie-agent-worker.js" eddie-agent-worker.js plain agent.js

echo "==> Build complete. Output:"
ls -lh "$PROJECT_ROOT/dist/"
