#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""Generate src/wordpiece_tables.rs from Python's `unicodedata`.

The WordPiece query tokenizer (src/wordpiece.rs) mirrors HF tokenizers'
BertNormalizer and BertPreTokenizer without the `unicode-normalization` and
`unicode_categories` crates, so the lite WASM build carries only the Unicode
data it needs:

  DECOMP_SINGLE / DECOMP_MULTI: characters with a canonical (NFD)
      decomposition, mapped to the base characters left after every combining
      mark (Mn/Mc/Me) is removed from the fully decomposed form. Hangul
      syllables are decomposed arithmetically in code and are not listed.
  MARKS: inclusive ranges of general category Mn/Mc/Me.
  PUNCT: inclusive ranges of general category P* above U+007F (ASCII is inline).
  OTHER: inclusive ranges of general category C* (Cc, Cf, Cn, Co, Cs) above
      U+007F; `tokenizers` deletes these as "control" characters (its
      `is_control` is `unicode_categories::is_other`), ASCII Cc is inline.

Usage: python3 scripts/gen_unicode_tables.py > src/wordpiece_tables.rs
"""
import sys
import unicodedata


def is_mark(c):
    return unicodedata.category(c) in ("Mn", "Mc", "Me")


def main():
    decomp_single = []
    decomp_multi = []
    marks = []
    punct = []
    other = []
    for cp in range(0x110000):
        c = chr(cp)
        cat = unicodedata.category(c)
        if cat in ("Mn", "Mc", "Me"):
            if marks and marks[-1][1] == cp - 1:
                marks[-1][1] = cp
            else:
                marks.append([cp, cp])
            continue  # marks are dropped before decomposition is consulted
        if cat.startswith("P") and cp > 0x7F:
            if punct and punct[-1][1] == cp - 1:
                punct[-1][1] = cp
            else:
                punct.append([cp, cp])
        if cat.startswith("C") and cp > 0x7F:
            if other and other[-1][1] == cp - 1:
                other[-1][1] = cp
            else:
                other.append([cp, cp])
        if 0xAC00 <= cp <= 0xD7A3:
            continue
        nfd = unicodedata.normalize("NFD", c)
        if nfd == c:
            continue
        base = "".join(ch for ch in nfd if not is_mark(ch))
        if base == c:
            continue
        if len(base) == 1:
            decomp_single.append((cp, ord(base)))
        else:
            decomp_multi.append((cp, base))

    out = []
    out.append("// SPDX-License-Identifier: GPL-3.0-only")
    out.append("")
    out.append("//! Generated by `scripts/gen_unicode_tables.py` from Python's `unicodedata`")
    out.append(f"//! (Unicode {unicodedata.unidata_version}); do not edit by hand.")
    out.append("//!")
    out.append("//! The subset of Unicode data [`crate::wordpiece`] needs to reproduce HF")
    out.append("//! tokenizers' `BertNormalizer` (accent stripping) and `BertPreTokenizer`")
    out.append("//! (punctuation isolation) without the `unicode-normalization` tables.")
    out.append("")

    def pairs(name, doc, rows, fmt):
        for line in doc:
            out.append(f"/// {line}")
        out.append(f"pub(crate) const {name}: &[{fmt}] = &[")
        line = "   "
        for a, b in rows:
            item = f" (0x{a:X}, 0x{b:X}),"
            if len(line) + len(item) > 96:
                out.append(line)
                line = "   "
            line += item
        out.append(line)
        out.append("];")
        out.append("")

    pairs(
        "DECOMP_SINGLE",
        [
            "Characters whose mark-free canonical decomposition is one character:",
            "`(char, base)`, sorted by char.",
        ],
        decomp_single,
        "(u32, u32)",
    )
    out.append("/// Characters whose mark-free canonical decomposition is several")
    out.append("/// characters, sorted by char.")
    out.append("pub(crate) const DECOMP_MULTI: &[(u32, &str)] = &[")
    for cp, s in decomp_multi:
        esc = "".join(f"\\u{{{ord(ch):X}}}" for ch in s)
        out.append(f'    (0x{cp:X}, "{esc}"),')
    out.append("];")
    out.append("")
    pairs("MARKS", ["Inclusive ranges of general category Mn, Mc and Me, sorted."], marks, "(u32, u32)")
    pairs("PUNCT", ["Inclusive ranges of general category P* above U+007F, sorted."], punct, "(u32, u32)")
    pairs(
        "OTHER",
        [
            "Inclusive ranges of general category Cc, Cf, Cn, Co and Cs above U+007F,",
            "sorted (what `tokenizers` deletes as control characters).",
        ],
        other,
        "(u32, u32)",
    )
    sys.stdout.write("\n".join(out))
    print(
        f"decomp single {len(decomp_single)}, multi {len(decomp_multi)}, "
        f"mark ranges {len(marks)}, punct ranges {len(punct)}, other ranges {len(other)}",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
