// SPDX-License-Identifier: GPL-3.0-only

//! A BERT WordPiece tokenizer for the query side of the sparse arm, built
//! from a `tokenizer.json` with `serde_json` alone.
//!
//! It reproduces what the `tokenizers` crate does for BERT-style files:
//! `BertNormalizer` (clean text, pad CJK characters with spaces, strip
//! accents, lowercase), `BertPreTokenizer` (split on whitespace, isolate
//! punctuation), greedy longest-match WordPiece with a `##` continuation
//! prefix, `[UNK]` for words that cannot be covered, and the
//! `max_input_chars_per_word` cap. Added tokens (`[SEP]`, `[MASK]`, ...)
//! typed literally in the text are matched before normalisation and encoded
//! to their ids, as the `tokenizers` crate does; the `[CLS]`/`[SEP]` a
//! post-processor would wrap around the sequence are never emitted (the
//! sparse query never scores them). Token ids therefore match the
//! `tokenizers` crate's `encode(text, true)` minus the tokens its
//! post-processor added; the native test
//! `matches_tokenizers_crate_on_real_vocab` checks 200 queries.
//!
//! The Unicode data it needs (canonical decompositions for accent
//! stripping, mark and punctuation categories) lives in
//! [`crate::wordpiece_tables`], generated by `scripts/gen_unicode_tables.py`,
//! so the lite WASM build does not carry the `unicode-normalization` tables.

use std::collections::HashMap;

use anyhow::{Context, Result, bail};
use serde_json::Value;

use crate::wordpiece_tables::{DECOMP_MULTI, DECOMP_SINGLE, MARKS, OTHER, PUNCT};

/// Fallback when `model.max_input_chars_per_word` is absent (HF default).
const DEFAULT_MAX_INPUT_CHARS: usize = 100;
/// Fallback when `model.continuing_subword_prefix` is absent (HF default).
const DEFAULT_PREFIX: &str = "##";

/// The basic-tokenizer flags of a `BertNormalizer`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct Normalizer {
    pub clean_text: bool,
    pub handle_chinese_chars: bool,
    pub strip_accents: bool,
    pub lowercase: bool,
}

/// One entry of `added_tokens`: matched literally in the raw text.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AddedToken {
    pub content: String,
    pub id: u32,
    pub special: bool,
}

/// Everything but the vocabulary: what an index stores next to the token
/// list in its `sparse/vocab` section so the runtime can rebuild the
/// tokenizer without `tokenizer.json`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WordPieceConfig {
    pub normalizer: Normalizer,
    pub unk_id: u32,
    /// `[CLS]` / `[SEP]` the post-processor adds (informational: the query
    /// side never emits them).
    pub cls_id: Option<u32>,
    pub sep_id: Option<u32>,
    pub max_input_chars: usize,
    /// Continuation prefix (`##`).
    pub prefix: String,
    pub added: Vec<AddedToken>,
    /// Content tokens kept per text.
    pub max_tokens: usize,
}

/// BERT WordPiece tokenizer (see the module docs).
#[derive(Debug, Clone)]
pub struct WordPiece {
    vocab: HashMap<String, u32>,
    /// Continuing tokens keyed without their prefix (`##ing` → `ing`).
    continuing: HashMap<String, u32>,
    unk_id: u32,
    cls_id: Option<u32>,
    sep_id: Option<u32>,
    max_input_chars: usize,
    prefix: String,
    normalizer: Normalizer,
    /// `added_tokens`, longest content first so overlapping matches prefer
    /// the longer token.
    added: Vec<AddedToken>,
    /// Content tokens kept per text (`max_seq_len` minus the special tokens
    /// the post-processor adds).
    max_tokens: usize,
}

impl WordPiece {
    /// Parse a `tokenizer.json`. `max_seq_len` is the encoder's sequence
    /// cap including special tokens (512 for BERT); it overrides the file's
    /// own `truncation` block like `prepare_tokenizer` does natively.
    pub fn from_tokenizer_json(bytes: &[u8], max_seq_len: usize) -> Result<Self> {
        let root: Value = serde_json::from_slice(bytes).context("parsing tokenizer.json")?;
        let model = root
            .get("model")
            .filter(|m| m.is_object())
            .context("tokenizer.json has no model object")?;
        let model_type = model.get("type").and_then(Value::as_str).unwrap_or("");
        if model_type != "WordPiece" {
            bail!(
                "tokenizer.json model type {:?} is not WordPiece",
                model_type
            );
        }
        let vocab_json = model
            .get("vocab")
            .and_then(Value::as_object)
            .context("tokenizer.json model has no vocab object")?;
        let prefix = model
            .get("continuing_subword_prefix")
            .and_then(Value::as_str)
            .unwrap_or(DEFAULT_PREFIX);
        let mut vocab = HashMap::with_capacity(vocab_json.len());
        for (token, id) in vocab_json {
            let id = id
                .as_u64()
                .and_then(|v| u32::try_from(v).ok())
                .with_context(|| format!("vocab entry {:?} has no u32 id", token))?;
            vocab.insert(token.clone(), id);
        }
        let unk_token = model
            .get("unk_token")
            .and_then(Value::as_str)
            .unwrap_or("[UNK]");
        let unk_id = *vocab
            .get(unk_token)
            .with_context(|| format!("unk_token {:?} is not in the vocab", unk_token))?;
        let max_input_chars = model
            .get("max_input_chars_per_word")
            .and_then(Value::as_u64)
            .map(|v| v as usize)
            .unwrap_or(DEFAULT_MAX_INPUT_CHARS);

        let normalizer = parse_normalizer(root.get("normalizer"))?;
        check_pre_tokenizer(root.get("pre_tokenizer"))?;
        let specials_added = post_processor_special_count(root.get("post_processor"));
        let (cls_id, sep_id) = post_processor_cls_sep(root.get("post_processor"), &vocab);

        let added: Vec<AddedToken> = root
            .get("added_tokens")
            .and_then(Value::as_array)
            .map(|list| {
                list.iter()
                    .filter_map(|t| {
                        let content = t.get("content")?.as_str()?;
                        let id = u32::try_from(t.get("id")?.as_u64()?).ok()?;
                        let special = t.get("special").and_then(Value::as_bool).unwrap_or(false);
                        (!content.is_empty()).then(|| AddedToken {
                            content: content.to_string(),
                            id,
                            special,
                        })
                    })
                    .collect()
            })
            .unwrap_or_default();

        Self::assemble(
            vocab,
            WordPieceConfig {
                normalizer,
                unk_id,
                cls_id,
                sep_id,
                max_input_chars,
                prefix: prefix.to_string(),
                added,
                max_tokens: max_seq_len.max(1).saturating_sub(specials_added).max(1),
            },
        )
    }

    /// Rebuild a tokenizer from its vocabulary in id order (an empty string
    /// marks an unused id) and its config, as stored in an index's
    /// `sparse/vocab` section.
    pub fn from_vocab(tokens: Vec<String>, config: WordPieceConfig) -> Result<Self> {
        let mut vocab = HashMap::with_capacity(tokens.len());
        for (id, token) in tokens.into_iter().enumerate() {
            if token.is_empty() {
                continue;
            }
            let id = u32::try_from(id).context("vocab has more than u32::MAX entries")?;
            vocab.insert(token, id);
        }
        Self::assemble(vocab, config)
    }

    /// The vocabulary in id order (gaps as empty strings) and the config:
    /// the inverse of [`WordPiece::from_vocab`].
    pub fn to_vocab(&self) -> (Vec<String>, WordPieceConfig) {
        let max_id = self
            .vocab
            .values()
            .copied()
            .max()
            .map_or(0, |m| m as usize + 1);
        let mut tokens = vec![String::new(); max_id];
        for (token, &id) in &self.vocab {
            tokens[id as usize] = token.clone();
        }
        let mut added = self.added.clone();
        added.sort_by_key(|t| t.id);
        (
            tokens,
            WordPieceConfig {
                normalizer: self.normalizer,
                unk_id: self.unk_id,
                cls_id: self.cls_id,
                sep_id: self.sep_id,
                max_input_chars: self.max_input_chars,
                prefix: self.prefix.clone(),
                added,
                max_tokens: self.max_tokens,
            },
        )
    }

    fn assemble(vocab: HashMap<String, u32>, config: WordPieceConfig) -> Result<Self> {
        let mut continuing = HashMap::new();
        if !config.prefix.is_empty() {
            for (token, &id) in &vocab {
                if let Some(rest) = token.strip_prefix(config.prefix.as_str())
                    && !rest.is_empty()
                {
                    continuing.insert(rest.to_string(), id);
                }
            }
        }
        if !vocab.values().any(|&id| id == config.unk_id) {
            bail!("unk id {} is not in the vocab", config.unk_id);
        }
        let mut added = config.added;
        added.retain(|t| !t.content.is_empty());
        added.sort_by_key(|t| std::cmp::Reverse(t.content.len()));
        Ok(Self {
            vocab,
            continuing,
            unk_id: config.unk_id,
            cls_id: config.cls_id,
            sep_id: config.sep_id,
            max_input_chars: config.max_input_chars,
            prefix: config.prefix,
            normalizer: config.normalizer,
            added,
            max_tokens: config.max_tokens.max(1),
        })
    }

    /// Id of a vocabulary token (exact string, including any `##` prefix).
    pub fn token_to_id(&self, token: &str) -> Option<u32> {
        self.vocab.get(token).copied()
    }

    pub fn vocab_size(&self) -> usize {
        self.vocab.len()
    }

    /// Ids of the special tokens (`added_tokens` flagged `special`).
    pub fn special_ids(&self) -> Vec<u32> {
        let mut ids: Vec<u32> = self
            .added
            .iter()
            .filter(|t| t.special)
            .map(|t| t.id)
            .collect();
        ids.sort_unstable();
        ids.dedup();
        ids
    }

    /// Token ids of `text` in order (no post-processor `[CLS]`/`[SEP]`),
    /// truncated to the sequence cap.
    pub fn encode(&self, text: &str) -> Vec<u32> {
        let mut ids = Vec::new();
        for piece in self.split_added(text) {
            match piece {
                Piece::Added(tok) => ids.push(tok.id),
                Piece::Text(raw) => {
                    let normalized = self.normalize(raw);
                    for word in pre_tokenize(&normalized) {
                        self.word_pieces(word, &mut ids);
                    }
                }
            }
            if ids.len() >= self.max_tokens {
                break;
            }
        }
        ids.truncate(self.max_tokens);
        ids
    }

    /// Split the raw text on literal occurrences of the added tokens.
    fn split_added<'a>(&'a self, text: &'a str) -> Vec<Piece<'a>> {
        let mut out = Vec::new();
        if self.added.is_empty() {
            out.push(Piece::Text(text));
            return out;
        }
        let mut rest = text;
        while !rest.is_empty() {
            let mut best: Option<(usize, &AddedToken)> = None;
            for tok in &self.added {
                if let Some(pos) = rest.find(tok.content.as_str())
                    && best.is_none_or(|(p, _)| pos < p)
                {
                    best = Some((pos, tok));
                }
            }
            match best {
                Some((pos, tok)) => {
                    if pos > 0 {
                        out.push(Piece::Text(&rest[..pos]));
                    }
                    out.push(Piece::Added(tok));
                    rest = &rest[pos + tok.content.len()..];
                }
                None => {
                    out.push(Piece::Text(rest));
                    break;
                }
            }
        }
        out
    }

    /// `BertNormalizer`, in its order: clean text, pad CJK characters,
    /// strip accents, lowercase.
    fn normalize(&self, text: &str) -> String {
        let n = &self.normalizer;
        let mut s: String = if n.clean_text {
            text.chars()
                .filter(|&c| c != '\0' && c != '\u{fffd}' && !is_control(c))
                .map(|c| if c.is_whitespace() { ' ' } else { c })
                .collect()
        } else {
            text.to_string()
        };
        if n.handle_chinese_chars {
            let mut padded = String::with_capacity(s.len() + 8);
            for c in s.chars() {
                if is_chinese_char(c) {
                    padded.push(' ');
                    padded.push(c);
                    padded.push(' ');
                } else {
                    padded.push(c);
                }
            }
            s = padded;
        }
        if n.strip_accents {
            let mut stripped = String::with_capacity(s.len());
            for c in s.chars() {
                push_base_chars(c, &mut stripped);
            }
            s = stripped;
        }
        if n.lowercase {
            s = s.chars().flat_map(char::to_lowercase).collect();
        }
        s
    }

    /// Greedy longest-match WordPiece of one pre-token.
    fn word_pieces(&self, word: &str, out: &mut Vec<u32>) {
        if word.chars().count() > self.max_input_chars {
            out.push(self.unk_id);
            return;
        }
        let mut pieces = Vec::new();
        let mut start = 0usize;
        while start < word.len() {
            let mut end = word.len();
            let mut found = None;
            while start < end {
                let sub = &word[start..end];
                let hit = if start == 0 {
                    self.vocab.get(sub)
                } else {
                    self.continuing.get(sub)
                };
                if let Some(&id) = hit {
                    found = Some(id);
                    break;
                }
                end -= sub.chars().next_back().map_or(1, char::len_utf8);
            }
            match found {
                Some(id) => {
                    pieces.push(id);
                    start = end;
                }
                None => {
                    out.push(self.unk_id);
                    return;
                }
            }
        }
        out.extend(pieces);
    }
}

enum Piece<'a> {
    Text(&'a str),
    Added(&'a AddedToken),
}

fn parse_normalizer(value: Option<&Value>) -> Result<Normalizer> {
    let mut n = Normalizer {
        clean_text: false,
        handle_chinese_chars: false,
        strip_accents: false,
        lowercase: false,
    };
    fn apply(n: &mut Normalizer, v: &Value) -> Result<()> {
        let kind = v.get("type").and_then(Value::as_str).unwrap_or("");
        let flag =
            |name: &str, default: bool| v.get(name).and_then(Value::as_bool).unwrap_or(default);
        match kind {
            "BertNormalizer" => {
                n.clean_text = flag("clean_text", true);
                n.handle_chinese_chars = flag("handle_chinese_chars", true);
                n.lowercase = flag("lowercase", true);
                // HF: `strip_accents` null means "same as lowercase".
                n.strip_accents = match v.get("strip_accents") {
                    Some(Value::Bool(b)) => *b,
                    _ => n.lowercase,
                };
            }
            "Lowercase" => n.lowercase = true,
            "StripAccents" => n.strip_accents = true,
            "Sequence" => {
                for step in v
                    .get("normalizers")
                    .and_then(Value::as_array)
                    .into_iter()
                    .flatten()
                {
                    apply(n, step)?;
                }
            }
            other => bail!(
                "tokenizer.json normalizer {:?} is not supported (expected BertNormalizer)",
                other
            ),
        }
        Ok(())
    }
    match value {
        None | Some(Value::Null) => {}
        Some(v) => apply(&mut n, v)?,
    }
    Ok(n)
}

fn check_pre_tokenizer(value: Option<&Value>) -> Result<()> {
    let kind = value
        .and_then(|v| v.get("type"))
        .and_then(Value::as_str)
        .unwrap_or("");
    if kind != "BertPreTokenizer" {
        bail!(
            "tokenizer.json pre_tokenizer {:?} is not supported (expected BertPreTokenizer)",
            kind
        );
    }
    Ok(())
}

/// The `[CLS]` / `[SEP]` ids a post-processor wraps around a sequence.
fn post_processor_cls_sep(
    value: Option<&Value>,
    vocab: &HashMap<String, u32>,
) -> (Option<u32>, Option<u32>) {
    let Some(v) = value else { return (None, None) };
    let pair_id = |key: &str| {
        v.get(key)
            .and_then(Value::as_array)
            .and_then(|pair| pair.get(1))
            .and_then(Value::as_u64)
            .and_then(|id| u32::try_from(id).ok())
    };
    match v.get("type").and_then(Value::as_str).unwrap_or("") {
        "BertProcessing" | "RobertaProcessing" => (pair_id("cls"), pair_id("sep")),
        "TemplateProcessing" => {
            let special_id = |name: &str| {
                v.get("special_tokens")
                    .and_then(|s| s.get(name))
                    .and_then(|s| s.get("ids"))
                    .and_then(Value::as_array)
                    .and_then(|ids| ids.first())
                    .and_then(Value::as_u64)
                    .and_then(|id| u32::try_from(id).ok())
                    .or_else(|| vocab.get(name).copied())
            };
            (special_id("[CLS]"), special_id("[SEP]"))
        }
        _ => (None, None),
    }
}

/// Special tokens the post-processor adds around a single sequence: they
/// count against the sequence cap the way HF truncation does.
fn post_processor_special_count(value: Option<&Value>) -> usize {
    let Some(v) = value else { return 0 };
    match v.get("type").and_then(Value::as_str).unwrap_or("") {
        "BertProcessing" | "RobertaProcessing" => 2,
        "TemplateProcessing" => v
            .get("single")
            .and_then(Value::as_array)
            .map(|steps| {
                steps
                    .iter()
                    .filter(|s| s.get("SpecialToken").is_some())
                    .count()
            })
            .unwrap_or(0),
        _ => 0,
    }
}

/// `BertPreTokenizer`: whitespace-separated words with every punctuation
/// character isolated as its own word.
fn pre_tokenize(text: &str) -> Vec<&str> {
    let mut words = Vec::new();
    let mut start: Option<usize> = None;
    for (i, c) in text.char_indices() {
        if c.is_whitespace() {
            if let Some(s) = start.take() {
                words.push(&text[s..i]);
            }
        } else if is_bert_punctuation(c) {
            if let Some(s) = start.take() {
                words.push(&text[s..i]);
            }
            words.push(&text[i..i + c.len_utf8()]);
        } else if start.is_none() {
            start = Some(i);
        }
    }
    if let Some(s) = start {
        words.push(&text[s..]);
    }
    words
}

/// `tokenizers`' notion of a control character: general category C*
/// (control, format, unassigned, private use), except the tab and line
/// breaks it counts as whitespace. Zero-width and soft-hyphen format
/// characters are deleted, not split on.
fn is_control(c: char) -> bool {
    if matches!(c, '\t' | '\n' | '\r') {
        return false;
    }
    if c.is_ascii() {
        return c.is_ascii_control();
    }
    in_ranges(OTHER, c)
}

fn is_chinese_char(c: char) -> bool {
    matches!(
        c as u32,
        0x4E00..=0x9FFF
            | 0x3400..=0x4DBF
            | 0x20000..=0x2A6DF
            | 0x2A700..=0x2B73F
            | 0x2B740..=0x2B81F
            | 0x2B920..=0x2CEAF
            | 0xF900..=0xFAFF
            | 0x2F800..=0x2FA1F
    )
}

fn in_ranges(ranges: &[(u32, u32)], c: char) -> bool {
    let cp = c as u32;
    let idx = ranges.partition_point(|&(_, hi)| hi < cp);
    ranges.get(idx).is_some_and(|&(lo, _)| lo <= cp)
}

fn is_combining_mark(c: char) -> bool {
    in_ranges(MARKS, c)
}

fn is_bert_punctuation(c: char) -> bool {
    c.is_ascii_punctuation() || (!c.is_ascii() && in_ranges(PUNCT, c))
}

/// NFD-decompose `c` and push the characters that are not combining marks
/// (HF `do_strip_accents`).
fn push_base_chars(c: char, out: &mut String) {
    if is_combining_mark(c) {
        return;
    }
    let cp = c as u32;
    if let (0xAC00..=0xD7A3, Some(s)) = (cp, hangul_jamo(cp)) {
        out.push_str(&s);
        return;
    }
    if let Ok(i) = DECOMP_SINGLE.binary_search_by_key(&cp, |&(from, _)| from) {
        if let Some(base) = char::from_u32(DECOMP_SINGLE[i].1) {
            out.push(base);
        }
        return;
    }
    if let Ok(i) = DECOMP_MULTI.binary_search_by_key(&cp, |&(from, _)| from) {
        out.push_str(DECOMP_MULTI[i].1);
        return;
    }
    out.push(c);
}

/// Algorithmic decomposition of a precomposed Hangul syllable into its
/// leading, vowel and (optional) trailing jamo.
fn hangul_jamo(cp: u32) -> Option<String> {
    const S_BASE: u32 = 0xAC00;
    const L_BASE: u32 = 0x1100;
    const V_BASE: u32 = 0x1161;
    const T_BASE: u32 = 0x11A7;
    const T_COUNT: u32 = 28;
    const N_COUNT: u32 = 21 * T_COUNT;
    let s = cp.checked_sub(S_BASE)?;
    if s >= 19 * N_COUNT {
        return None;
    }
    let l = char::from_u32(L_BASE + s / N_COUNT)?;
    let v = char::from_u32(V_BASE + (s % N_COUNT) / T_COUNT)?;
    let t = s % T_COUNT;
    let mut out = String::with_capacity(9);
    out.push(l);
    out.push(v);
    if t != 0 {
        out.push(char::from_u32(T_BASE + t)?);
    }
    Some(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    const TINY: &str = r###"{
      "version": "1.0",
      "truncation": null, "padding": null,
      "added_tokens": [
        {"id": 0, "content": "[PAD]", "single_word": false, "lstrip": false, "rstrip": false, "normalized": false, "special": true},
        {"id": 1, "content": "[CLS]", "single_word": false, "lstrip": false, "rstrip": false, "normalized": false, "special": true},
        {"id": 2, "content": "[SEP]", "single_word": false, "lstrip": false, "rstrip": false, "normalized": false, "special": true},
        {"id": 3, "content": "[UNK]", "single_word": false, "lstrip": false, "rstrip": false, "normalized": false, "special": true}
      ],
      "normalizer": {"type": "BertNormalizer", "clean_text": true, "handle_chinese_chars": true, "strip_accents": null, "lowercase": true},
      "pre_tokenizer": {"type": "BertPreTokenizer"},
      "post_processor": {"type": "BertProcessing", "sep": ["[SEP]", 2], "cls": ["[CLS]", 1]},
      "decoder": null,
      "model": {"type": "WordPiece", "unk_token": "[UNK]", "continuing_subword_prefix": "##", "max_input_chars_per_word": 100,
        "vocab": {"[PAD]": 0, "[CLS]": 1, "[SEP]": 2, "[UNK]": 3, "new": 4, "york": 5, "weather": 6,
                  "un": 7, "##believ": 8, "##able": 9, ",": 10, "!": 11, "中": 12, "文": 13, "3": 14, "##0": 15,
                  "cafe": 16, "##s": 17, "‘": 18, "a": 19, "b": 20, "c": 21}}
    }"###;

    fn tiny() -> WordPiece {
        WordPiece::from_tokenizer_json(TINY.as_bytes(), 512).unwrap()
    }

    #[test]
    fn greedy_longest_match_with_continuation_prefix() {
        let t = tiny();
        assert_eq!(t.encode("unbelievable"), vec![7, 8, 9]);
        assert_eq!(
            t.encode("New York weather, new york!"),
            vec![4, 5, 6, 10, 4, 5, 11]
        );
        // A word with an uncoverable piece becomes [UNK] as a whole.
        assert_eq!(t.encode("unbelievably"), vec![3]);
        assert_eq!(t.encode("30 300"), vec![14, 15, 14, 15, 15]);
    }

    #[test]
    fn normalizer_strips_accents_pads_cjk_and_lowercases() {
        let t = tiny();
        assert_eq!(t.encode("Cafés"), vec![16, 17]);
        assert_eq!(t.encode("CAFÉS"), vec![16, 17]);
        // Combining mark written separately is dropped too.
        assert_eq!(t.encode("cafe\u{301}s"), vec![16, 17]);
        assert_eq!(t.encode("中文weather"), vec![12, 13, 6]);
        // Control and format characters vanish, other whitespace splits.
        assert_eq!(t.encode("new\u{1}york\u{a0}weather"), vec![3, 6]);
        assert_eq!(t.encode("new\u{200b}york\u{ad} weather"), vec![3, 6]);
        assert_eq!(t.encode("new\tyork\u{2003}weather"), vec![4, 5, 6]);
        // Unicode punctuation is isolated like ASCII punctuation.
        assert_eq!(t.encode("‘new’"), vec![18, 4, 3]);
    }

    #[test]
    fn literal_added_tokens_split_the_text_and_keep_their_id() {
        let t = tiny();
        assert_eq!(t.encode("new[SEP]york"), vec![4, 2, 5]);
        assert_eq!(t.encode("[CLS] weather [SEP]"), vec![1, 6, 2]);
        assert_eq!(t.special_ids(), vec![0, 1, 2, 3]);
    }

    #[test]
    fn long_words_are_unk_and_output_is_capped() {
        let t = tiny();
        let long = "a".repeat(101);
        assert_eq!(t.encode(&long), vec![3]);
        let capped = WordPiece::from_tokenizer_json(TINY.as_bytes(), 4).unwrap();
        // 4 minus [CLS]/[SEP] leaves two content tokens.
        assert_eq!(capped.encode("a b c a b c"), vec![19, 20]);
    }

    #[test]
    fn vocab_parts_round_trip() {
        let t = tiny();
        let (tokens, config) = t.to_vocab();
        assert_eq!(tokens.len(), 22);
        assert_eq!(tokens[4], "new");
        assert_eq!(config.unk_id, 3);
        assert_eq!((config.cls_id, config.sep_id), (Some(1), Some(2)));
        assert_eq!(config.prefix, "##");
        assert_eq!(config.max_input_chars, 100);
        assert_eq!(config.max_tokens, 510);
        assert!(config.normalizer.lowercase && config.normalizer.strip_accents);
        assert_eq!(config.added.len(), 4);
        let back = WordPiece::from_vocab(tokens, config).unwrap();
        for text in [
            "New York weather, new york!",
            "unbelievable Cafés 中文weather 30",
            "new[SEP]york ‘new’",
        ] {
            assert_eq!(back.encode(text), t.encode(text), "{:?}", text);
        }
        // A gap in the id space is an unused id, not a token.
        let mut tokens = vec![String::new(); 6];
        tokens[1] = "[UNK]".into();
        tokens[5] = "hi".into();
        let sparse_ids = WordPiece::from_vocab(
            tokens,
            WordPieceConfig {
                normalizer: Normalizer::default(),
                unk_id: 1,
                cls_id: None,
                sep_id: None,
                max_input_chars: 100,
                prefix: "##".into(),
                added: vec![],
                max_tokens: 510,
            },
        )
        .unwrap();
        assert_eq!(sparse_ids.encode("hi ho"), vec![5, 1]);
        assert_eq!(sparse_ids.vocab_size(), 2);
    }

    #[test]
    fn hangul_syllables_decompose_to_jamo() {
        let mut s = String::new();
        push_base_chars('한', &mut s);
        assert_eq!(s, "\u{1112}\u{1161}\u{11AB}");
        s.clear();
        push_base_chars('가', &mut s);
        assert_eq!(s, "\u{1100}\u{1161}");
    }

    #[test]
    fn rejects_non_wordpiece_files() {
        let json = r#"{"model": {"type": "BPE", "vocab": {}}}"#;
        let err = WordPiece::from_tokenizer_json(json.as_bytes(), 512).unwrap_err();
        assert!(err.to_string().contains("not WordPiece"));
    }

    /// Cross-check against the `tokenizers` crate on a synthetic vocabulary
    /// that exercises every normalizer and pre-tokenizer path.
    #[cfg(not(target_arch = "wasm32"))]
    #[test]
    fn matches_tokenizers_crate_on_tiny_vocab() {
        let ours = tiny();
        let mut hf = tokenizers::Tokenizer::from_bytes(TINY.as_bytes()).unwrap();
        crate::embed::prepare_tokenizer(&mut hf, 512).unwrap();
        for text in [
            "New York weather, new york!",
            "unbelievable unbelievably",
            "Cafés CAFÉS cafe\u{301}s",
            "中文weather 30 300",
            "new\u{1}york\u{a0}weather ‘new’",
            "new[SEP]york [CLS] weather [SEP]",
            "a\u{300}b c",
            "",
            "   ",
            "!!!",
        ] {
            assert_eq!(
                ours.encode(text),
                hf_content_ids(&hf, text),
                "text {:?}",
                text
            );
        }
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub(crate) fn hf_content_ids(hf: &tokenizers::Tokenizer, text: &str) -> Vec<u32> {
        let enc = hf.encode(text, true).unwrap();
        let mask = enc.get_special_tokens_mask();
        enc.get_ids()
            .iter()
            .enumerate()
            .filter(|(i, _)| mask.get(*i).copied().unwrap_or(0) == 0)
            .map(|(_, &id)| id)
            .collect()
    }

    /// Queries for the real-vocabulary parity test: ASCII, accents,
    /// punctuation, numbers, CJK, Hangul, emoji, special tokens.
    #[cfg(not(target_arch = "wasm32"))]
    const PARITY_SEEDS: &[&str] = &[
        "What's the weather in New York now?",
        "how do i configure the search widget on a hugo site",
        "Eddie builds a semantic index at build time.",
        "rust wasm bundle size optimisation",
        "café résumé naïve façade coöperate",
        "Crème brûlée à la française",
        "Straße groß Müller Ärger Öl Übung",
        "señor niño mañana jalapeño",
        "Đặng Thị Ngọc Hà — Việt Nam",
        "Łódź Kraków Gdańsk Wrocław",
        "İstanbul ışık Diyarbakır",
        "Ærø Ørsted Ångström",
        "Ελληνικά καλημέρα κόσμε",
        "Привет мир, как дела?",
        "中文分词测试",
        "日本語のテキストを検索する",
        "한국어 검색 엔진",
        "混合 mixed 文本 text 123",
        "email me at jason@example.com!",
        "https://www.jason-grey.com/posts/eddie-0.4/",
        "C++ vs C# vs Rust: which is faster?",
        "price: $1,234.56 (approx. €1.1k)",
        "1/2 + 3/4 = 1.25; 10% off",
        "the year 2026-08-29T23:00:00Z",
        "\"quoted\" 'single' «guillemets» “curly”",
        "hyphen-ated words and under_scores",
        "ellipsis… dash— en–dash",
        "tabs\tand\nnewlines\r\nhere",
        "emoji 🚀 rocket 🔥 fire",
        "[CLS] special [SEP] tokens [MASK] [PAD]",
        "UPPERCASE lowercase MiXeD",
        "a b c d e f g",
        "supercalifragilisticexpialidocious antidisestablishmentarianism",
        "pneumonoultramicroscopicsilicovolcanoconiosis",
        "   leading and trailing spaces   ",
        "multiple     spaces    between",
        "zero\u{200b}width\u{200b}space",
        "control\u{1}chars\u{7f}here",
        "soft\u{ad}hyphen",
        "ﬁne ﬂow ligatures",
        "ＦＵＬＬＷＩＤＴＨ ｌａｔｉｎ １２３",
        "① ② ③ circled numbers",
        "math: ∑ ∫ √ ∞ ≠ ≤",
        "arrows → ← ↑ ↓",
        "currency ¥ £ ₹ ₿",
        "trademark™ copyright© registered®",
        "fractions ½ ¼ ¾",
        "ä ö ü ß in isolation",
        "e\u{301} decomposed e-acute",
        "n\u{303} decomposed n-tilde",
        "ǅ ǈ ǋ titlecase digraphs",
        "Ω ω Σ σ ς",
        "थाई ไทย tiếng Việt",
        "عربي עברית",
        "the quick brown fox jumps over the lazy dog",
        "how to bake sourdough bread at home",
        "kubernetes pod crashloopbackoff fix",
        "what is reciprocal rank fusion",
        "jason grey consulting improbability engineers",
        "who wrote this site?",
        "SELECT * FROM users WHERE id = 1;",
        "fn main() { println!(\"hi\"); }",
        "cargo build --release --target wasm32-unknown-unknown",
        "brotli vs gzip compression ratio",
        "int8 quantised dense vectors",
        "BM25 k1=1.2 b=0.75",
        "1st 2nd 3rd 4th",
        "3.14159 2.71828 1e-9",
        "phone +1 (612) 555-0199",
    ];

    /// Parity with the `tokenizers` crate on the real sparse vocabulary
    /// (200+ queries). Needs the model in the HuggingFace cache:
    /// `cargo test -- --ignored matches_tokenizers_crate_on_real_vocab`.
    #[cfg(not(target_arch = "wasm32"))]
    #[test]
    #[ignore] // requires network access or the HuggingFace cache
    fn matches_tokenizers_crate_on_real_vocab() {
        let repo =
            crate::embed::hub::ModelRepo::open(crate::models::DEFAULT_SPARSE_MODEL, None).unwrap();
        let bytes = std::fs::read(repo.get("tokenizer.json").unwrap()).unwrap();
        let ours = WordPiece::from_tokenizer_json(&bytes, 512).unwrap();
        let mut hf = tokenizers::Tokenizer::from_bytes(&bytes).unwrap();
        crate::embed::prepare_tokenizer(&mut hf, 512).unwrap();
        let mut queries: Vec<String> = Vec::new();
        queries.push("x".repeat(101));
        for seed in PARITY_SEEDS {
            queries.push(seed.to_string());
            queries.push(seed.to_uppercase());
            queries.push(format!("«{}»? Ça va… {}!", seed, seed.len()));
        }
        assert!(queries.len() >= 200, "{} queries", queries.len());
        let (vocab_tokens, config) = ours.to_vocab();
        let rebuilt = WordPiece::from_vocab(vocab_tokens, config).unwrap();
        let mut tokens = 0usize;
        for q in &queries {
            let expected = hf_content_ids(&hf, q);
            let got = ours.encode(q);
            tokens += expected.len();
            assert_eq!(got, expected, "query {:?}", q);
            assert_eq!(
                rebuilt.encode(q),
                expected,
                "rebuilt tokenizer, query {:?}",
                q
            );
        }
        eprintln!(
            "wordpiece parity: {} queries, {} tokens, all ids identical",
            queries.len(),
            tokens
        );
    }
}
